<?php
require_once 'PHPUnit/Framework.php';
/**
 * Test class for Model.
 * Generated by PHPUnit on 2009-04-20 at 11:26:56.
 */
class InflectorTest extends PHPUnit_Framework_TestCase {			  /**			 * Sets up the fixture, for example, opens a network connection.			 * This method is called before a test is executed.			 *			 * @access protected			 */			protected function setUp()  {			}						public function testPlurals() {				$pluralTests = array('City' => 'Cities',				                     'Country' => 'Countries',				                     'Nut' => 'Nuts');				foreach($pluralTests as $singular => $plural)					$this->assertEquals($plural, Inflector::getPlural($singular));			}			  /**			 * Tears down the fixture, for example, closes a network connection.			 * This method is called after a test is executed.			 *			 * @access protected			 */			protected function tearDown() {			}
}
?>
