<?php
require_once 'PHPUnit/Framework.php';

require_once 'ConcreteModelsTestSuite.php';
require_once 'City.class.php';
/**
 * Test class for City.
 * Generated by PHPUnit on 2009-04-20 at 13:21:47.
 */
class CityTest extends PHPUnit_Framework_TestCase
{

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
	}
		public function testObjectCreation() {
		$denmark = new Country(1);
		$this->assertEquals('Denmark', $denmark->name);
		$city = new City;
		$city->name = 'Aarhus';
		$city->country = $denmark->id;
		$city->postalCode = 8000;
		$this->assertNotNull($city->id);
		$cityID = $city->id;
		$cityName = $city->name;
		unset($city);
		$city = new City($cityID);
		$this->assertEquals('Aarhus', $cityName);
	}
		public function testObjectUpdate() {
		$city = new City(1);
		$this->assertEquals('Aarhus', $city->name);
		$this->assertEquals(8000, $city->postalCode);
		$this->assertEquals(1, $city->country);
		$city->name = 'Andeby';
		$city->postalCode = 1234;
		unset($city);
		$city = new City(1);
		$this->assertEquals('Andeby', $city->name);
		$this->assertEquals(1234, $city->postalCode);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
	}
}
?>
