<?php
require_once 'PHPUnit/Framework.php';

require_once 'ConcreteModelsTestSuite.php';
require_once 'Country.class.php';
/**
 * Test class for Country.
 * Generated by PHPUnit on 2009-04-20 at 13:22:19.
 */
class CountryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var    Country
	 * @access protected
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
		ConcreteModelsTestSuite::$mysqli->query('START TRANSACTION;');
	}

	public function testObjectCreationFailOnNull() {
		$this->setExpectedException('MySQLBadNullException', "Column 'name' cannot be null");
		$country = new Country;
		$country->name;
	}

	public function testObjectCreation() {
		$country = new Country;
		$country->name = 'France';
		$this->assertNotNull($country->id);
		$countryID = $country->id;
		unset($country);
		$country = new Country($countryID);
		$this->assertEquals('France', $country->name);
	}

	public function testObjectInitFailOnUndefined() {
		$this->setExpectedException('UndefinedPrimaryKeyException', 'The primary key you specified is not represented in the database.');
		$country = new Country(0);
		$country->name;
	}
	
	public function testPrimaryKeyChange() {
		$poland = new Country;
		$poland->name = 'Poland';
		$countryID = $poland->id;
		unset($poland);
		$poland = new Country($countryID);
		$poland->id = 1000;
		unset($poland);
		$poland = new Country(1000);
		$this->assertEquals('Poland', $poland->name);
	}
	
	public function testEquality() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
		ConcreteModelsTestSuite::$mysqli->query('ROLLBACK;');
	}
}
?>
