<?php
require_once 'PHPUnit/Framework.php';

require_once 'ConcreteModelsTestSuite.php';
require_once 'Country.class.php';
/**
 * Test class for Country.
 * Generated by PHPUnit on 2009-04-20 at 13:22:19.
 */
class CountryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var    Country
	 * @access protected
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp()
	{
		//$this->object = new Country;
	}

	public function testObjectCreationFailOnNull() {
		$this->setExpectedException('MySQLBadNullException', 'Column \'name\' cannot be null');
		$country = new Country;
		$country->name;
	}

	public function testObjectCreation() {
		$country = new Country;
		$country->name = 'Denmark';
		$this->assertNotNull($country->id);
		$countryID = $country->id;
		unset($country);
		$country = new Country($countryID);
		$this->assertEquals('Denmark', $country->name);
	}

	public function testObjectInitFailOnUndefined() {
		$this->setExpectedException('UndefinedPrimaryKeysException', 'The primary key(-s) you specified are not represented in the database.');
		$country = new Country(0);
		$country->name;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown()
	{
	}
}
?>
