<?php
require_once 'PHPUnit/Framework.php';

require_once 'ConcreteModelsTestSuite.php';
require_once 'Customer.class.php';
/**
 * Test class for Customer.
 * Generated by PHPUnit on 2009-05-31 at 14:29:58.
 */
class CustomerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Customer
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        //$this->object = new Customer;
    }
    
    public function testConcurrency() {
    	$customer1 = new Customer;
    	$customer1->firstName = 'Anders';
    	$customer1->lastName = 'And';
    	$customer1->address = 'Paradisæblevej 111';
    	$customer1->email = 'anders.and@andenet.dk';
    	$customer1->city = 1;
    	$this->assertNotNull($customer1->address);
    	$customer2 = new Customer($customer1->id);
    	$customer2->address = 'Paradisæblevej 112';
    	$this->assertEquals('Paradisæblevej 112', $customer1->address);
    	$customer1->address = 'Paradisæblevej 111';
    }
    
    public function testConcurrency2() {
    	$customer3 = new Customer;
    	$customer3->firstName = 'Fedtmule';
    	$customer3->lastName = 'ingenting';
    	$customer3->address = 'Mulevænget 3';
    	$customer3->email = 'fedtmule@andenet.dk';
    	$customer3->id = 5;
    	$customer4 = new Customer(5);
    	$customer4->city = 1;
    	$this->assertEquals('Mulevænget 3', $customer4->address);
    	$customer4->lastName = 'noget';
    	$this->assertEquals('noget', $customer3->lastName);
    	$this->assertEquals('noget', $customer4->lastName);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }
}
?>
